---

- name: Define CD device
  ansible.builtin.set_fact:
    cd: '/dev/sr0'

- name: Recheck if CD/DVD is mounted  # noqa no-free-form
  ansible.builtin.shell: |
    set -o pipefail
    df | awk '$1=="{{ cd }}" {print $NF}'
  check_mode: False
  changed_when: False
  register: mounted

- name: Mount CD/DVD
  ansible.posix.mount:
    src: "{{ cd }}"
    path: /mnt
    state: mounted
    fstype: iso9660
    opts: ro,noauto
  when: mounted.stdout | length == 0

- name: Recheck if CD/DVD is mounted  # noqa no-free-form
  ansible.builtin.shell: |
    set -o pipefail
    df | awk '$1=="{{ cd }}" {print $NF}'
  check_mode: False
  changed_when: False
  register: mounted

- name: Fail if nothing found
  ansible.builtin.fail:
    msg: "Unable to find virtualbox guest cd/dvd '{{ cd }}'"
  when: mounted.stdout | length == 0

- name: Set installer location
  ansible.builtin.set_fact:
    installer: "{{ mounted.stdout }}/VBoxLinuxAdditions.run"
