---

- name: Define CD device
  set_fact:
    cd: '/dev/sr0'

- name: Recheck if CD/DVD is mounted # noqa 306
  shell: df | awk '$1=="{{ cd }}" {print $NF}'
  check_mode: False
  changed_when: False
  register: mounted

- name: Mount CD/DVD
  mount:
    src: "{{ cd }}"
    path: /mnt
    state: mounted
    fstype: iso9660
    opts: ro,noauto
  when: mounted.stdout|length == 0

- name: Recheck if CD/DVD is mounted # noqa 306
  shell: df | awk '$1=="{{ cd }}" {print $NF}'
  check_mode: False
  changed_when: False
  register: mounted

- name: Fail if nothing found
  fail:
    msg: "Unable to find virtualbox guest cd/dvd '{{ cd }}'"
  when: mounted.stdout|length == 0

- name: Set installer location
  set_fact:
    installer: "{{ mounted.stdout }}/VBoxLinuxAdditions.run"
