---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Update all packages
  ansible.builtin.include_role:
    name: package
  vars:
    package_mode: upgrade-verbose

- name: Reboot if package was removed
  ansible.builtin.include_role:
    name: reboot
  when:
    - ansible_connection != 'local'
    - ansible_virtualization_type not in [ 'docker', 'container', 'containerd' ]
  tags: molecule-idempotence-notest

# - name: Reboot server to deactivate kernel modules
#   fail:
#     msg: "Please reboot to deactivate kernel modules"
#   when: virtbox_package is changed and ansible_connection == 'local'

- name: Install build tools needed for compilation
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ virtualbox_guest_packages }}"

- name: Remove distro provided packages
  ansible.builtin.package:
    name: "{{ virtualbox_guest_obsolete_packages }}"
    state: absent
  register: virtbox_package

- name: Get installed virtualbox guest version
  ansible.builtin.shell: |
    set -o pipefail
    modinfo vboxguest | awk '/^version:/ {print $2}'
  args:
    executable: /bin/bash
  check_mode: False
  changed_when: False
  failed_when: False
  register: virtbox_guest_installed

- name: Run code for {{ virtbox_method }}
  ansible.builtin.include_tasks: "{{ virtbox_method }}.yml"

- name: Get virtualbox guest version available
  ansible.builtin.shell: |
    set -o pipefail
    {{ installer }} --info | awk '/^Identification:/ {print $3}'
  args:
    executable: /bin/bash
  check_mode: False
  changed_when: False
  failed_when: False
  register: virtbox_guest_available

- name: Show virtualbox guest versions
  ansible.builtin.debug:
    msg:
      installer: "{{ installer }}"
      version installed: "{{ virtbox_guest_installed.stdout }}"
      version available: "{{ virtbox_guest_available.stdout }}"

- name: Compilation
  when: virtbox_guest_installed.stdout|length == 0 or virtbox_guest_installed.stdout != virtbox_guest_available.stdout or force_virtbox_guest|bool
  tags: molecule-idempotence-notest
  block:

    - name: Compile & install virtualbox guest additions
      ansible.builtin.shell: |
        { coproc tee { tee /tmp/virtbox.log ;} >&3 ;} 3>&1
         exec >&${tee[1]} 2>&1
        REMOVE_INSTALLATION_DIR=0 {{ installer }}
      args:
        executable: /bin/bash
      failed_when: virtbox_guest_install.rc == 1 or virtbox_guest_install.rc > 2
      register: virtbox_guest_install
      tags:
        - skip_ansible_lint

    - name: Display output of command
      ansible.builtin.debug:
        msg: "{{ virtbox_guest_install.stdout_lines }}"

- name: Unmount again
  ansible.posix.mount:
    state: absent
    path: /mnt
  when: virtbox_method == 'cd'

- name: Reboot if new virtualbox guest additions were compiled
  ansible.builtin.reboot:
  when:
    - virtbox_guest_install is changed and not skip_reboot
    - ansible_connection != 'local'
    - ansible_virtualization_type not in [ 'docker', 'container', 'containerd' ]
