---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    gnome_desktop_wayland: False
    gnome_desktop_autologin_enable: True
    gnome_desktop_autologin: vagrant
    gnome_desktop_lock_disable: True
    gnome_desktop_lock_timeout: 0
  pre_tasks:
    - name: Create 'remote_tmp'
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: "0700"
  roles:
    - gnome_desktop
  tasks:
    - name: Include role 'ansible-role-virtualbox_guest'
      include_role:
        name: ansible-role-virtualbox_guest
