---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    gnome_desktop_wayland: False
    gnome_desktop_autologin_enable: True
    gnome_desktop_autologin: vagrant
    gnome_desktop_lock_disable: True
    gnome_desktop_lock_timeout: 0
  roles:
    - gnome_desktop
  tasks:
    - name: Include role 'ansible-role-virtualbox_guest'
      ansible.builtin.include_role:
        name: ansible-role-virtualbox_guest
